import java.awt.*;
import java.awt.event.ActionEvent; //ActionEvent is a class in Java that is a part of the java.awt.event package. 
                                   //It represents an event that is generated when a component, such as a button, menu item, or text field, is activated (When the user interacts with it).
import java.awt.event.ActionListener;//is an interface in java that belongs to the 'java.awt.event'.
                                     //The ActionListener interface is designed to handle action events, which are generated by user actions such as clicking a button or selecting a menu item.
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

class MyActionListener implements ActionListener{
    @Override//Overriding the ActionListener class method. When the button in the frame is clicked, the terminal will show 'Button clicked'.
    public void actionPerformed(ActionEvent e){
        System.out.println("Button clicked");
    }
}
class WindowEent{
    public static void main(String[] args) {
        Frame f = new Frame("Basis program");
        
        TextField t = new TextField();
        t.setBounds(60, 50, 170,20);
        
        Button b = new Button("Click me");
        b.setBounds(100, 120, 80, 30);

        MyActionListener actionListener = new MyActionListener();
        b.addActionListener(actionListener);

        f.add(t);
        f.add(b);
        f.setSize(300, 300);
        f.setLayout(null);
        f.setVisible(true);

        f.addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent e){
				System.exit(0);
			}
		});

    }
}
